# Generated by Django 5.2.5 on 2025-09-02 21:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_readings', models.IntegerField(default=0)),
                ('avg_battery_level', models.FloatField(default=0)),
                ('connectivity_uptime', models.FloatField(default=0)),
                ('data_quality_score', models.FloatField(default=0)),
                ('alerts_triggered', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Métrica de Dispositivo',
                'verbose_name_plural': 'Métricas de Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampling_interval', models.IntegerField(default=300, verbose_name='Intervalo de Muestreo (s)')),
                ('data_retention', models.IntegerField(default=30, verbose_name='Retención de Datos (días)')),
                ('alert_thresholds', models.JSONField(default=dict, verbose_name='Umbrales de Alerta')),
                ('gps_enabled', models.BooleanField(default=True, verbose_name='GPS Habilitado')),
                ('health_monitoring', models.BooleanField(default=True, verbose_name='Monitoreo de Salud')),
                ('low_power_mode', models.BooleanField(default=False, verbose_name='Modo Bajo Consumo')),
                ('firmware_auto_update', models.BooleanField(default=False, verbose_name='Actualización Automática')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Configuración de Dispositivo',
                'verbose_name_plural': 'Configuraciones de Dispositivo',
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CONNECT', 'Conexión'), ('DISCONNECT', 'Desconexión'), ('LOW_BATTERY', 'Batería Baja'), ('MAINTENANCE', 'Mantenimiento'), ('ERROR', 'Error'), ('FIRMWARE_UPDATE', 'Actualización de Firmware'), ('LOCATION_UPDATE', 'Actualización de Ubicación'), ('HEALTH_ALERT', 'Alerta de Salud')], max_length=20, verbose_name='Tipo de Evento')),
                ('severity', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], default='LOW', max_length=10, verbose_name='Severidad')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Datos Adicionales')),
                ('resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto el')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp del Evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Evento de Dispositivo',
                'verbose_name_plural': 'Eventos de Dispositivo',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GPSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Altitud (m)')),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precisión (m)')),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Velocidad (km/h)')),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Rumbo (°)')),
                ('satellites', models.IntegerField(blank=True, null=True, verbose_name='Satélites')),
                ('hdop', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='HDOP')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp del Dispositivo')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('blockchain_hash', models.CharField(blank=True, max_length=66, null=True, validators=[core.models.validate_transaction_hash], verbose_name='Hash Blockchain')),
            ],
            options={
                'verbose_name': 'Datos GPS',
                'verbose_name_plural': 'Datos GPS',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HealthSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Ritmo Cardíaco (BPM)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura (°C)')),
                ('movement_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Actividad de Movimiento')),
                ('rumination_time', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de Rumia (min)')),
                ('feeding_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Actividad de Alimentación')),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, verbose_name='Ritmo Respiratorio')),
                ('posture', models.CharField(blank=True, max_length=50, verbose_name='Postura')),
                ('ambient_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura Ambiental (°C)')),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad (%)')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp del Dispositivo')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('blockchain_hash', models.CharField(blank=True, max_length=66, null=True, validators=[core.models.validate_transaction_hash], verbose_name='Hash Blockchain')),
                ('processed', models.BooleanField(default=False, verbose_name='Procesado')),
                ('health_alert', models.BooleanField(default=False, verbose_name='Alerta de Salud')),
            ],
            options={
                'verbose_name': 'Datos de Salud',
                'verbose_name_plural': 'Datos de Salud',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='ID del Dispositivo')),
                ('device_type', models.CharField(choices=[('TEMPERATURE', 'Sensor de Temperatura'), ('HEART_RATE', 'Sensor de Ritmo Cardíaco'), ('MOVEMENT', 'Sensor de Movimiento'), ('GPS', 'Sensor de Ubicación'), ('MULTI', 'Sensor Multifunción'), ('CARAVANA', 'Caravana Inteligente'), ('GATEWAY', 'Gateway IoT')], max_length=20, verbose_name='Tipo de Dispositivo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Dispositivo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('MAINTENANCE', 'En Mantenimiento'), ('DISCONNECTED', 'Desconectado'), ('LOW_BATTERY', 'Batería Baja')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('firmware_version', models.CharField(default='1.0.0', max_length=50, verbose_name='Versión de Firmware')),
                ('battery_level', models.IntegerField(blank=True, null=True, verbose_name='Nivel de Batería (%)')),
                ('last_reading', models.DateTimeField(blank=True, null=True, verbose_name='Última Lectura')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Ubicación')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='Dirección MAC')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Dispositivo IoT',
                'verbose_name_plural': 'Dispositivos IoT',
                'ordering': ['-created_at'],
            },
        ),
    ]
