# Generated by Django 5.2.5 on 2025-09-01 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(choices=[('GPS', 'Dispositivo GPS'), ('SENSOR', 'Sensor de Salud'), ('CARAVANA', 'Caravana Inteligente'), ('GATEWAY', 'Gateway IoT')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('firmware_version', models.CharField(default='1.0.0', max_length=50)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installed_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cattle.animal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo IoT',
                'verbose_name_plural': 'Dispositivos IoT',
            },
        ),
        migrations.CreateModel(
            name='HealthSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('activity_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rumination_time', models.IntegerField(blank=True, null=True)),
                ('feeding_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('timestamp', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.animal')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.iotdevice')),
            ],
            options={
                'verbose_name': 'Datos de Salud',
                'verbose_name_plural': 'Datos de Salud',
            },
        ),
        migrations.CreateModel(
            name='GPSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('timestamp', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.animal')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.iotdevice')),
            ],
            options={
                'verbose_name': 'Datos GPS',
                'verbose_name_plural': 'Datos GPS',
                'indexes': [models.Index(fields=['animal', 'timestamp'], name='iot_gpsdata_animal__200b79_idx'), models.Index(fields=['device', 'timestamp'], name='iot_gpsdata_device__89d4f0_idx')],
            },
        ),
    ]
