# Generated by Django 5.2.5 on 2025-09-02 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0002_initial'),
        ('iot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceevent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por'),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_data', to='cattle.animal', verbose_name='Animal'),
        ),
        migrations.AddField(
            model_name='healthsensordata',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to='cattle.animal', verbose_name='Animal'),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iot_devices', to='cattle.animal', verbose_name='Animal Asociado'),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_devices', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AddField(
            model_name='healthsensordata',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to='iot.iotdevice', verbose_name='Dispositivo'),
        ),
        migrations.AddField(
            model_name='gpsdata',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_data', to='iot.iotdevice', verbose_name='Dispositivo'),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='iot.iotdevice', verbose_name='Dispositivo'),
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='iot.iotdevice', verbose_name='Dispositivo'),
        ),
        migrations.AddField(
            model_name='deviceanalytics',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='iot.iotdevice'),
        ),
        migrations.AddIndex(
            model_name='iotdevice',
            index=models.Index(fields=['device_id'], name='iot_iotdevi_device__c4fcba_idx'),
        ),
        migrations.AddIndex(
            model_name='iotdevice',
            index=models.Index(fields=['device_type'], name='iot_iotdevi_device__03acc5_idx'),
        ),
        migrations.AddIndex(
            model_name='iotdevice',
            index=models.Index(fields=['status'], name='iot_iotdevi_status_7cf4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='iotdevice',
            index=models.Index(fields=['animal'], name='iot_iotdevi_animal__b4d390_idx'),
        ),
        migrations.AddIndex(
            model_name='iotdevice',
            index=models.Index(fields=['owner'], name='iot_iotdevi_owner_i_2e132c_idx'),
        ),
        migrations.AddIndex(
            model_name='iotdevice',
            index=models.Index(fields=['last_reading'], name='iot_iotdevi_last_re_696c57_idx'),
        ),
        migrations.AddIndex(
            model_name='healthsensordata',
            index=models.Index(fields=['animal', 'timestamp'], name='iot_healths_animal__e7a18d_idx'),
        ),
        migrations.AddIndex(
            model_name='healthsensordata',
            index=models.Index(fields=['device', 'timestamp'], name='iot_healths_device__67c888_idx'),
        ),
        migrations.AddIndex(
            model_name='healthsensordata',
            index=models.Index(fields=['timestamp'], name='iot_healths_timesta_1e4f92_idx'),
        ),
        migrations.AddIndex(
            model_name='healthsensordata',
            index=models.Index(fields=['health_alert'], name='iot_healths_health__55a35e_idx'),
        ),
        migrations.AddIndex(
            model_name='healthsensordata',
            index=models.Index(fields=['processed'], name='iot_healths_process_e9c431_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsdata',
            index=models.Index(fields=['animal', 'timestamp'], name='iot_gpsdata_animal__200b79_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsdata',
            index=models.Index(fields=['device', 'timestamp'], name='iot_gpsdata_device__89d4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='gpsdata',
            index=models.Index(fields=['timestamp'], name='iot_gpsdata_timesta_15f898_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['device', 'timestamp'], name='iot_devicee_device__0f5e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['event_type'], name='iot_devicee_event_t_012d86_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['severity'], name='iot_devicee_severit_93ec2e_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['resolved'], name='iot_devicee_resolve_37f279_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceanalytics',
            unique_together={('device', 'date')},
        ),
    ]
