# Generated by Django 5.2.5 on 2025-09-03 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0002_initial'),
        ('iot', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='auth_token',
            field=models.CharField(blank=True, help_text='Token para autenticación API de dispositivos', max_length=100, verbose_name='Token de Autenticación'),
        ),
        migrations.AddIndex(
            model_name='iotdevice',
            index=models.Index(fields=['auth_token'], name='iot_iotdevi_auth_to_695eb6_idx'),
        ),
    ]
