/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ganadoRegistryUpgradeableSol from "./GanadoRegistryUpgradeable.sol";
export type { ganadoRegistryUpgradeableSol };
export type { AnimalNFTUpgradeable } from "./AnimalNFTUpgradeable";
export type { GanadoTokenUpgradeable } from "./GanadoTokenUpgradeable";
