# Generated by Django 5.2.5 on 2025-08-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_tag', models.CharField(max_length=100, unique=True, verbose_name='Arete')),
                ('breed', models.CharField(max_length=100, verbose_name='Raza')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (kg)')),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Sano'), ('SICK', 'Enfermo'), ('RECOVERING', 'Recuperándose')], default='HEALTHY', max_length=20, verbose_name='Estado de Salud')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('ipfs_hash', models.CharField(blank=True, max_length=255, verbose_name='Hash IPFS')),
                ('blockchain_tx', models.CharField(blank=True, max_length=255, verbose_name='Transacción Blockchain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Lote')),
                ('origin', models.CharField(max_length=255, verbose_name='Origen')),
                ('destination', models.CharField(max_length=255, verbose_name='Destino')),
                ('status', models.CharField(choices=[('CREATED', 'Creado'), ('IN_TRANSIT', 'En Tránsito'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado'), ('PROCESSING', 'Procesando'), ('QUALITY_CHECK', 'Control de Calidad')], default='CREATED', max_length=20, verbose_name='Estado')),
                ('ipfs_hash', models.CharField(blank=True, max_length=255, verbose_name='Hash IPFS')),
                ('blockchain_tx', models.CharField(blank=True, max_length=255, verbose_name='Transacción Blockchain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
    ]
