# Generated by Django 5.2.5 on 2025-09-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_tag', models.CharField(max_length=100, unique=True, verbose_name='Arete')),
                ('breed', models.CharField(max_length=100, verbose_name='Raza')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (kg)')),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Sano'), ('SICK', 'Enfermo'), ('RECOVERING', 'Recuperándose'), ('UNDER_OBSERVATION', 'En Observación'), ('QUARANTINED', 'En Cuarentena')], default='HEALTHY', max_length=20, verbose_name='Estado de Salud')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('ipfs_hash', models.CharField(blank=True, max_length=255, verbose_name='Hash IPFS')),
                ('token_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Token ID NFT')),
                ('mint_transaction_hash', models.CharField(blank=True, max_length=66, verbose_name='Transacción de Mint')),
                ('nft_owner_wallet', models.CharField(blank=True, max_length=42, verbose_name='Wallet Owner NFT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
            },
        ),
        migrations.CreateModel(
            name='AnimalHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Sano'), ('SICK', 'Enfermo'), ('RECOVERING', 'Recuperándose'), ('UNDER_OBSERVATION', 'En Observación'), ('QUARANTINED', 'En Cuarentena')], max_length=20)),
                ('source', models.CharField(choices=[('VETERINARIAN', 'Veterinario'), ('IOT_SENSOR', 'Sensor IoT'), ('FARMER', 'Granjero'), ('SYSTEM', 'Sistema Automático')], default='VETERINARIAN', max_length=20)),
                ('iot_device_id', models.CharField(blank=True, max_length=100, verbose_name='ID Dispositivo IoT')),
                ('notes', models.TextField(blank=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura (°C)')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Ritmo Cardíaco (bpm)')),
                ('movement_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Actividad de Movimiento')),
                ('ipfs_hash', models.CharField(blank=True, max_length=100, verbose_name='Hash IPFS')),
                ('transaction_hash', models.CharField(blank=True, max_length=66, verbose_name='Hash de Transacción')),
                ('blockchain_hash', models.CharField(blank=True, max_length=66, null=True, verbose_name='Hash Blockchain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Salud',
                'verbose_name_plural': 'Registros de Salud',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Lote')),
                ('origin', models.CharField(max_length=255, verbose_name='Origen')),
                ('destination', models.CharField(max_length=255, verbose_name='Destino')),
                ('status', models.CharField(choices=[('CREATED', 'Creado'), ('IN_TRANSIT', 'En Tránsito'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado'), ('PROCESSING', 'Procesando'), ('QUALITY_CHECK', 'Control de Calidad')], default='CREATED', max_length=20, verbose_name='Estado')),
                ('ipfs_hash', models.CharField(blank=True, max_length=255, verbose_name='Hash IPFS')),
                ('blockchain_tx', models.CharField(blank=True, max_length=66, verbose_name='Transacción Blockchain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
    ]
