# Generated by Django 5.2.5 on 2025-08-31 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL, verbose_name='Dueño'),
        ),
        migrations.AddField(
            model_name='batch',
            name='animals',
            field=models.ManyToManyField(related_name='batches', to='cattle.animal', verbose_name='Animales'),
        ),
        migrations.AddField(
            model_name='batch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['ear_tag'], name='cattle_anim_ear_tag_774463_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['owner'], name='cattle_anim_owner_i_a96790_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['health_status'], name='cattle_anim_health__a7d63e_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status'], name='cattle_batc_status_e7da4f_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['created_by'], name='cattle_batc_created_458176_idx'),
        ),
    ]
