# Generated by Django 5.2.5 on 2025-09-02 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0002_initial'),
        ('cattle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL, verbose_name='Dueño'),
        ),
        migrations.AddField(
            model_name='animalhealthrecord',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='cattle.animal'),
        ),
        migrations.AddField(
            model_name='animalhealthrecord',
            name='veterinarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='animals',
            field=models.ManyToManyField(related_name='batches', to='cattle.animal', verbose_name='Animales'),
        ),
        migrations.AddField(
            model_name='batch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='animal',
            name='current_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_animals', to='cattle.batch', verbose_name='Lote Actual'),
        ),
        migrations.AddField(
            model_name='blockchaineventstate',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blockchain.blockchainevent'),
        ),
        migrations.AddField(
            model_name='cattleaudittrail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='animalhealthrecord',
            index=models.Index(fields=['animal', 'created_at'], name='cattle_anim_animal__ede035_idx'),
        ),
        migrations.AddIndex(
            model_name='animalhealthrecord',
            index=models.Index(fields=['health_status'], name='cattle_anim_health__2917d6_idx'),
        ),
        migrations.AddIndex(
            model_name='animalhealthrecord',
            index=models.Index(fields=['iot_device_id'], name='cattle_anim_iot_dev_0190dc_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status'], name='cattle_batc_status_e7da4f_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['created_by'], name='cattle_batc_created_458176_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['ear_tag'], name='cattle_anim_ear_tag_774463_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['owner'], name='cattle_anim_owner_i_a96790_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['health_status'], name='cattle_anim_health__a7d63e_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['token_id'], name='cattle_anim_token_i_3e910d_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['health_status', 'owner'], name='cattle_anim_health__2ccb6a_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['nft_owner_wallet', 'token_id'], name='cattle_anim_nft_own_420d14_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['current_batch'], name='cattle_anim_current_a4dcf3_idx'),
        ),
        migrations.AddIndex(
            model_name='cattleaudittrail',
            index=models.Index(fields=['object_type', 'object_id'], name='cattle_catt_object__14f12d_idx'),
        ),
        migrations.AddIndex(
            model_name='cattleaudittrail',
            index=models.Index(fields=['timestamp'], name='cattle_catt_timesta_07b6d7_idx'),
        ),
        migrations.AddIndex(
            model_name='cattleaudittrail',
            index=models.Index(fields=['user', 'timestamp'], name='cattle_catt_user_id_022709_idx'),
        ),
    ]
