# Generated by Django 5.2.5 on 2025-09-01 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='blockchain_tx',
        ),
        migrations.AddField(
            model_name='animal',
            name='mint_transaction_hash',
            field=models.CharField(blank=True, max_length=255, verbose_name='Transacción de Mint'),
        ),
        migrations.AddField(
            model_name='animal',
            name='nft_owner_wallet',
            field=models.CharField(blank=True, max_length=255, verbose_name='Wallet Owner NFT'),
        ),
        migrations.AddField(
            model_name='animal',
            name='token_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Token ID NFT'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['token_id'], name='cattle_anim_token_i_3e910d_idx'),
        ),
    ]
