# Generated by Django 5.2.5 on 2025-09-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animales'},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
    ]
