# Generated by Django 5.2.5 on 2025-09-06 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0003_alter_animal_options_alter_batch_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='on_blockchain',
            field=models.BooleanField(default=False, verbose_name='En Blockchain'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['on_blockchain'], name='cattle_batc_on_bloc_f7d794_idx'),
        ),
    ]
