# Generated by Django 5.2.5 on 2025-09-11 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0004_batch_on_blockchain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('issuing_authority', models.CharField(max_length=200)),
                ('validity_days', models.IntegerField()),
                ('requirements', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cattle_certification_standard',
            },
        ),
        migrations.CreateModel(
            name='AnimalGeneticProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genetic_marker', models.CharField(blank=True, max_length=100)),
                ('breed_composition', models.JSONField(default=dict)),
                ('genetic_defects', models.JSONField(blank=True, null=True)),
                ('ipfs_hash', models.CharField(blank=True, max_length=255)),
                ('blockchain_hash', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genetic_profile', to='cattle.animal')),
                ('parent_female', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_female', to='cattle.animal')),
                ('parent_male', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_male', to='cattle.animal')),
            ],
            options={
                'db_table': 'cattle_animal_genetic_profile',
            },
        ),
        migrations.CreateModel(
            name='AnimalCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('evidence', models.JSONField(default=dict)),
                ('blockchain_hash', models.CharField(max_length=255)),
                ('revoked', models.BooleanField(default=False)),
                ('revocation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='cattle.animal')),
                ('certifying_authority', models.ForeignKey(limit_choices_to={'role': 'auditor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.certificationstandard')),
            ],
            options={
                'db_table': 'cattle_animal_certification',
                'indexes': [models.Index(fields=['animal', 'expiration_date'], name='cattle_anim_animal__72fe83_idx'), models.Index(fields=['certifying_authority', 'certification_date'], name='cattle_anim_certify_aa23b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feeding_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('blockchain_hash', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='cattle.animal')),
                ('supplier', models.ForeignKey(limit_choices_to={'role': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cattle_feeding_record',
                'indexes': [models.Index(fields=['animal', 'feeding_date'], name='cattle_feed_animal__5ae2e0_idx'), models.Index(fields=['supplier', 'feeding_date'], name='cattle_feed_supplie_5a738d_idx')],
            },
        ),
    ]
