# Generated by Django 5.2.6 on 2025-09-15 19:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0005_certificationstandard_animalgeneticprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalcertification',
            options={'verbose_name': 'Certificación de Animal', 'verbose_name_plural': 'Certificaciones de Animales'},
        ),
        migrations.AlterModelOptions(
            name='animalgeneticprofile',
            options={'verbose_name': 'Perfil Genético', 'verbose_name_plural': 'Perfiles Genéticos'},
        ),
        migrations.AlterModelOptions(
            name='certificationstandard',
            options={'verbose_name': 'Estándar de Certificación', 'verbose_name_plural': 'Estándares de Certificación'},
        ),
        migrations.AlterModelOptions(
            name='feedingrecord',
            options={'ordering': ['-feeding_date'], 'verbose_name': 'Registro de Alimentación', 'verbose_name_plural': 'Registros de Alimentación'},
        ),
        migrations.AlterField(
            model_name='animalcertification',
            name='blockchain_hash',
            field=models.CharField(blank=True, max_length=255, validators=[core.models.validate_transaction_hash]),
        ),
    ]
