# Generated by Django 5.2.6 on 2025-09-24 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0006_alter_animalcertification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcertification',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_certifications', to='cattle.animal'),
        ),
    ]
