# Generated by Django 5.2.6 on 2025-09-24 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0007_alter_animalcertification_animal'),
        ('core', '0002_blockchainnetwork_crosschainmanager_starknetcontract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalMultichain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_token_id', models.BigIntegerField(blank=True, null=True)),
                ('is_cross_chain', models.BooleanField(default=False)),
                ('last_cross_chain_sync', models.DateTimeField(blank=True, null=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multichain_data', to='cattle.animal')),
                ('primary_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.blockchainnetwork')),
            ],
            options={
                'verbose_name': 'Datos Multichain de Animal',
                'verbose_name_plural': 'Datos Multichain de Animales',
            },
        ),
        migrations.CreateModel(
            name='AnimalNFTMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.BigIntegerField()),
                ('mirror_transaction_hash', models.CharField(max_length=255)),
                ('mirror_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('animal_multichain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirrors', to='cattle.animalmultichain')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blockchainnetwork')),
            ],
            options={
                'verbose_name': 'Espejo de NFT',
                'verbose_name_plural': 'Espejos de NFT',
                'unique_together': {('animal_multichain', 'network')},
            },
        ),
    ]
