/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GanadoRegistryUpgradeable } from "./GanadoRegistryUpgradeable";
export type { IAnimalNFT } from "./IAnimalNFT";
export type { IGanadoToken } from "./IGanadoToken";
