# Generated by Django 5.2.5 on 2025-09-02 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
        ('cattle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainevent',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cattle.animal'),
        ),
        migrations.AddField(
            model_name='blockchainevent',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cattle.batch'),
        ),
        migrations.AddIndex(
            model_name='contractinteraction',
            index=models.Index(fields=['transaction_hash'], name='blockchain__transac_e36b38_idx'),
        ),
        migrations.AddIndex(
            model_name='contractinteraction',
            index=models.Index(fields=['caller_address'], name='blockchain__caller__c61987_idx'),
        ),
        migrations.AddIndex(
            model_name='contractinteraction',
            index=models.Index(fields=['contract_type', 'action_type'], name='blockchain__contrac_45a507_idx'),
        ),
        migrations.AddIndex(
            model_name='contractinteraction',
            index=models.Index(fields=['block_number'], name='blockchain__block_n_1da35a_idx'),
        ),
        migrations.AddIndex(
            model_name='gaspricehistory',
            index=models.Index(fields=['timestamp'], name='blockchain__timesta_e8f58e_idx'),
        ),
        migrations.AddIndex(
            model_name='gaspricehistory',
            index=models.Index(fields=['block_number'], name='blockchain__block_n_d2cf61_idx'),
        ),
        migrations.AddIndex(
            model_name='smartcontract',
            index=models.Index(fields=['address'], name='blockchain__address_fcf1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='smartcontract',
            index=models.Index(fields=['contract_type'], name='blockchain__contrac_3237fd_idx'),
        ),
        migrations.AddIndex(
            model_name='smartcontract',
            index=models.Index(fields=['is_active'], name='blockchain__is_acti_d4ab88_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionpool',
            index=models.Index(fields=['transaction_hash'], name='blockchain__transac_0c9a00_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionpool',
            index=models.Index(fields=['status'], name='blockchain__status_152454_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainevent',
            index=models.Index(fields=['transaction_hash'], name='blockchain__transac_873c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainevent',
            index=models.Index(fields=['animal', 'event_type'], name='blockchain__animal__1d6818_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainevent',
            index=models.Index(fields=['block_number'], name='blockchain__block_n_04e9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainevent',
            index=models.Index(fields=['created_at'], name='blockchain__created_94fb67_idx'),
        ),
    ]
