# Generated by Django 5.2.5 on 2025-09-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkstate',
            options={'ordering': ['-last_sync_time'], 'verbose_name': 'Estado de Red', 'verbose_name_plural': 'Estados de Red'},
        ),
    ]
