# Generated by Django 5.2.5 on 2025-09-11 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_alter_networkstate_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('proposal_type', models.CharField(choices=[('PARAMETER_CHANGE', 'Cambio de Parámetro'), ('UPGRADE', 'Actualización de Contrato'), ('GRANT', 'Concesión de Fondos'), ('POLICY', 'Cambio de Política')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voting_start', models.DateTimeField()),
                ('voting_end', models.DateTimeField()),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('blockchain_proposal_id', models.IntegerField(blank=True, null=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blockchain_governance_proposal',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_value', models.BooleanField()),
                ('voting_power', models.DecimalField(decimal_places=2, max_digits=20)),
                ('blockchain_vote_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='blockchain.governanceproposal')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blockchain_vote',
                'unique_together': {('proposal', 'voter')},
            },
        ),
    ]
