# Generated by Django 5.2.6 on 2025-09-24 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0007_alter_animalcertification_animal'),
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_scans', models.IntegerField()),
                ('premium_upgrades', models.IntegerField()),
                ('most_accessed_animals', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculation_method', models.CharField(max_length=100)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle.animal')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.certification')),
            ],
        ),
    ]
