/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ganadoRegistryUpgradeableSol from "./GanadoRegistryUpgradeable.sol";
export { AnimalNFTUpgradeable__factory } from "./AnimalNFTUpgradeable__factory";
export { GanadoTokenUpgradeable__factory } from "./GanadoTokenUpgradeable__factory";
