# Generated by Django 5.2.5 on 2025-09-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apitoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Token de API', 'verbose_name_plural': 'Tokens de API'},
        ),
        migrations.AlterModelOptions(
            name='reputationscore',
            options={'ordering': ['-last_calculated'], 'verbose_name': 'Puntuación de Reputación', 'verbose_name_plural': 'Puntuaciones de Reputación'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['-granted_at'], 'verbose_name': 'Rol Detallado de Usuario', 'verbose_name_plural': 'Roles Detallados de Usuario'},
        ),
    ]
