# Generated by Django 5.2.5 on 2025-09-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_apitoken_options_alter_reputationscore_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Preferencia de Usuario', 'verbose_name_plural': 'Preferencias de Usuario'},
        ),
    ]
