# Generated by Django 5.2.5 on 2025-09-11 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userpreference_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('action_id', models.IntegerField()),
                ('tokens_awarded', models.DecimalField(decimal_places=2, max_digits=20)),
                ('distribution_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_hash', models.CharField(max_length=255)),
                ('is_claimed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_reward_distribution',
            },
        ),
        migrations.CreateModel(
            name='StakingPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_staked', models.DecimalField(decimal_places=2, max_digits=20)),
                ('staking_start', models.DateTimeField()),
                ('staking_duration', models.IntegerField()),
                ('apy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rewards_earned', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('blockchain_staking_id', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staking_pool', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_staking_pool',
            },
        ),
    ]
