# Generated by Django 5.2.5 on 2025-09-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_animals', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('active_devices', models.IntegerField(default=0)),
                ('average_gas_price', models.FloatField(default=0)),
                ('blockchain_events', models.IntegerField(default=0)),
                ('health_alerts', models.IntegerField(default=0)),
                ('producer_count', models.IntegerField(default=0)),
                ('vet_count', models.IntegerField(default=0)),
                ('frigorifico_count', models.IntegerField(default=0)),
                ('auditor_count', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0)),
                ('error_rate', models.FloatField(default=0)),
                ('system_uptime', models.FloatField(default=100.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Métrica del Sistema',
                'verbose_name_plural': 'Métricas del Sistema',
                'ordering': ['-date'],
            },
        ),
    ]
