# Generated by Django 5.2.6 on 2025-09-24 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('network_id', models.CharField(choices=[('POLYGON_AMOY', 'Polygon Amoy (Testnet)'), ('POLYGON_MAINNET', 'Polygon Mainnet'), ('STARKNET_SEPOLIA', 'Starknet Sepolia'), ('STARKNET_MAINNET', 'Starknet Mainnet'), ('BITCOIN', 'Bitcoin'), ('ETHEREUM', 'Ethereum')], max_length=50, unique=True)),
                ('network_type', models.CharField(choices=[('EVM', 'EVM Compatible'), ('STARKNET', 'Starknet'), ('BITCOIN', 'Bitcoin')], max_length=20)),
                ('chain_id', models.BigIntegerField()),
                ('rpc_url', models.CharField(max_length=500)),
                ('explorer_url', models.CharField(max_length=500)),
                ('native_currency', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_testnet', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('config', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Red Blockchain',
                'verbose_name_plural': 'Redes Blockchain',
                'ordering': ['priority', 'network_id'],
            },
        ),
        migrations.CreateModel(
            name='CrossChainManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(max_length=100, unique=True)),
                ('operation_type', models.CharField(choices=[('BRIDGE', 'Bridge de Tokens'), ('STATE_SYNC', 'Sincronización de Estado'), ('NFT_MIRROR', 'Espejo de NFT'), ('DATA_VERIFICATION', 'Verificación de Datos')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_operations', to='core.blockchainnetwork')),
                ('target_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_operations', to='core.blockchainnetwork')),
            ],
            options={
                'verbose_name': 'Gestor Cross-Chain',
                'verbose_name_plural': 'Gestores Cross-Chain',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StarknetContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=100)),
                ('contract_version', models.CharField(default='1.0.0', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('interface_definition', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('deployment_block', models.BigIntegerField(default=0)),
                ('deployment_date', models.DateTimeField(auto_now_add=True)),
                ('class_hash', models.CharField(max_length=255, unique=True)),
                ('compiled_cairo_version', models.CharField(max_length=50)),
                ('account_address', models.CharField(max_length=255)),
                ('fee_token_address', models.CharField(default='0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7', max_length=255)),
                ('implementation_class_hash', models.CharField(blank=True, max_length=255)),
                ('proxy_class_hash', models.CharField(blank=True, max_length=255)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blockchainnetwork')),
            ],
            options={
                'verbose_name': 'Contrato Starknet',
                'verbose_name_plural': 'Contratos Starknet',
            },
        ),
        migrations.CreateModel(
            name='StarknetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=255, unique=True)),
                ('function_name', models.CharField(max_length=100)),
                ('calldata', models.JSONField(default=list)),
                ('max_fee', models.DecimalField(decimal_places=0, max_digits=30)),
                ('actual_fee', models.DecimalField(decimal_places=0, max_digits=30, null=True)),
                ('version', models.IntegerField(default=1)),
                ('signature', models.JSONField(default=list)),
                ('nonce', models.DecimalField(decimal_places=0, max_digits=30, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED_ON_L2', 'Accepted on L2'), ('ACCEPTED_ON_L1', 'Accepted on L1'), ('REJECTED', 'Rejected')], max_length=20)),
                ('block_number', models.BigIntegerField(null=True)),
                ('block_hash', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.starknetcontract')),
            ],
            options={
                'verbose_name': 'Transacción Starknet',
                'verbose_name_plural': 'Transacciones Starknet',
                'ordering': ['-block_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChainSpecificModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('chain_data', models.JSONField(default=dict)),
                ('transaction_hashes', models.JSONField(default=list)),
                ('block_numbers', models.JSONField(default=list)),
                ('is_synced', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blockchainnetwork')),
            ],
            options={
                'verbose_name': 'Modelo Específico de Cadena',
                'verbose_name_plural': 'Modelos Específicos de Cadena',
                'unique_together': {('content_type', 'object_id', 'network')},
            },
        ),
    ]
