/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAnimalNFT,
  IAnimalNFTInterface,
} from "../../../contracts/GanadoRegistryUpgradeable.sol/IAnimalNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAnimalNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IAnimalNFTInterface {
    return new Interface(_abi) as IAnimalNFTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAnimalNFT {
    return new Contract(address, _abi, runner) as unknown as IAnimalNFT;
  }
}
