/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGanadoToken,
  IGanadoTokenInterface,
} from "../../../contracts/GanadoRegistryUpgradeable.sol/IGanadoToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "batchId",
        type: "string",
      },
    ],
    name: "mintByDAO",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGanadoToken__factory {
  static readonly abi = _abi;
  static createInterface(): IGanadoTokenInterface {
    return new Interface(_abi) as IGanadoTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGanadoToken {
    return new Contract(address, _abi, runner) as unknown as IGanadoToken;
  }
}
