/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GanadoRegistryUpgradeable__factory } from "./GanadoRegistryUpgradeable__factory";
export { IAnimalNFT__factory } from "./IAnimalNFT__factory";
export { IGanadoToken__factory } from "./IGanadoToken__factory";
